### ISSUE TITLE
How can we disable the button?

### ISSUE THREAD

**Issue by benznext** [ziscloud/angular-bootstrap-toggle#10]
I would like to disable the button if the user has no rights to change it?

**Comment by LennyLip** [comment]
https://github.com/ziscloud/angular-bootstrap-toggle/issues/4#issuecomment-276497044

**Comment by bertysentry** [comment]
Please close as this was already implemented, thanks!

**Comment by bertysentry** [comment]
Please use `<toggle ng-disabled="true" ...></toggle>".
