### ISSUE TITLE
Width is not set correctly when toggle is inside a $uibModal.

### ISSUE THREAD

**Issue by jorgemarcondes** [ziscloud/angular-bootstrap-toggle#12]

**Comment by stevenwaskey** [comment]
This symptom _appears_ to occur whenever the `<toggle>` directive is used within a hidden element.  

I, too, am experiencing the same symptom, however I have the toggle inside a `<uib-dropdown-menu>` ...    I'll let you know if I come up with a viable solution.

**Comment by stevenwaskey** [comment]
I found an alternative approach that solved the issue without modifying the source code.

In my case, I'm using the `uib-dropdown` directive.  To alleviate the symptom, I simply incorporated the usage of the **is-open** attrib. 
eg( `<div uib-dropdown is-open="vm.isOpen"> ... <div>` )

I then added `vm.isOpen` as an **ng-if** eval to the `<toggle>` directive.

Final: 
```
<div uib-dropdown is-open="vm.isOpen" auto-close="disabled">
    <span uib-dropdown-toggle><i class="fa fa-pencil"></i></span>
    <div uib-dropdown-menu>
        <toggle ng-model="vm.toggleSwitchModel" size="btn-sm" ng-if="vm.isOpen"></toggle>
        <staff-color-picker ng-if="vm.enableColorPicker" colors="vm.colors"></staff-color-picker>
    </div>
</div>
```

**Comment by saltimbanc** [comment]
My solution was to show the toggle after the modal was rendered.
Here is an example:

JavaScript:

    function modalController($scope, $uibModalInstance) {
        $scope.local = {};
	$uibModalInstance.rendered.then(function(){
		$scope.local.rendered = true;
	});
    }

HTML:

    <toggle ng-if="local.rendered" ng-model="local.toggleModel"></toggle>

**Comment by xSkArx** [comment]
@saltimbanc  doesn't work for me, I use Angular 1.5.11, but using bootstrap js modal

**Comment by bertysentry** [comment]
This is fixed in version 0.4.0. Please close the issue to confirm the fix. Thanks!

**Comment by bertysentry** [comment]
This is actually fixed (for real now! ;-) ) in version 0.4.1 (published today).

**Comment by reinken** [comment]
I believe this issue has reappeared. See [this plunker](https://plnkr.co/edit/FiGz3FAC8sRVqAB3mz2B?p=preview)

**Comment by bertysentry** [comment]
Oh God... will we ever see the end of this? thank you for the plunker, I also reproduced the problem myself. We will need to find a new technique to properly calculate the size of the button.

**Comment by vickyrathee** [comment]
Still the size issue in 0.4.1 when using toggle in modal, loading page after progress bar using ng-show after 1-2 seconds. Same issue as in above plunker.

**Comment by bertysentry** [comment]
I'm working on it and good news: I have a working solution! :-) Stay tuned!

**Comment by bertysentry** [comment]
Guys, would you mind having a look at PR #44 which fixes the problem. `<toggle>` is now properly sized even when hidden (`ng-if`, `ng-show` and `$uibModal`, or even pure CSS).

Try using **dist/angular-bootstrap-toggle.min.js** from the [issue-12](https://github.com/ziscloud/angular-bootstrap-toggle/tree/issue-12-size/dist) branch.

**Comment by bertysentry** [comment]
Guys, the branch has been merged to master, so you can get it straight from there!
