### ISSUE TITLE
Javascript function to be called when toggle

### ISSUE THREAD

**Issue by gaurav1264** [ziscloud/angular-bootstrap-toggle#13]
I have below code where I want javascript function to be called when I toggle. 

> <toggle ng-model="system.complianceCategory" ng-change="changed()" size="btn-xs" on="Yes" off="No" onstyle="btn-success" offstyle="btn-default" ng-click="switchComplianceCategory(system)"></toggle>

system.complianceCategory can be either zero or one. When we click on toggle, I see toggle on/offs first then it calls to function, so In function it reverse the value of system.complianceCategory. 

Is there anyway where before toggle on/offs, I get the original system.complianceCategory value.

**Comment by bertysentry** [comment]
Please use `<toggle ng-change="myCallbackFunction()" ...></toggle>`.
