### ISSUE TITLE
how to use toggle directive in ng-repeat

### ISSUE THREAD

**Issue by nirmalgoswami** [ziscloud/angular-bootstrap-toggle#15]
Hello,

I am trying to use toggle directive in for loop and i have also set dynamic ng-model but still it toggle all buttons available in loop. it should toggle single button not all

Thanks

**Comment by shubhammakharia** [comment]
Check your ng-model directive and that it's serving boolean values. The current toggle library probably only supports boolean values, otherwise its sets all the toggles 'on'
