### ISSUE TITLE
Update package in NPM repo

### ISSUE THREAD

**Issue by pablodgonzalez** [ziscloud/angular-bootstrap-toggle#21]
The last versión in npm is 0.1.2. please if you could update the package it will be great!

**Comment by SidBala** [comment]
Yes please update @ziscloud

**Comment by bertysentry** [comment]
0.4.0 is now available on npmjs.com: https://www.npmjs.com/package/angular-bootstrap-toggle
Please close the issue to confirm it's resolved. Thanks!
