### ISSUE TITLE
Version 0.1.3 not available via bower

### ISSUE THREAD

**Issue by mark007** [ziscloud/angular-bootstrap-toggle#26]
Hi,

Is there plans to build the latest code into a new version available via npm. The latest available via npm / webpack is 0.1.2 seen on the right hand side here https://www.npmjs.com/package/angular-bootstrap-toggle

Bower is able to see the 0.1.3 release however.

Regards,
Mark

**Comment by bertysentry** [comment]
Version 0.4.1 is now available, thank you!
