### ISSUE TITLE
'style' property doesn't work

### ISSUE THREAD

**Issue by ViieeS** [ziscloud/angular-bootstrap-toggle#27]
Custom class doesn't set... Is `style` property deprecated?

**Comment by bertysentry** [comment]
_onstyle_ and _offstyle_ are deprecated since #32.
They are replaced with **on-class** and **off-class** respectively.
Thanks!

**Comment by ViieeS** [comment]
@bertysentry ok, thanks! Can you also update npm version of the package to the latest (`npm publish`)? It's 0.1.2 now...

**Comment by bertysentry** [comment]
I contributed to develop version 0.4.0 which fixed the issue you mentioned. @ziscloud published 0.4.0 on npmjs.com: https://www.npmjs.com/package/angular-bootstrap-toggle

Please close the issue to confirm it's resolved. Thanks!
