### ISSUE TITLE
toggle in hidden context

### ISSUE THREAD

**Issue by kvogelsa** [ziscloud/angular-bootstrap-toggle#3]
I'd like to use toggle within a hidden element (eg div) and use it on demand, after the element is made visible. The problem is, that the toggle's size does not fit with its content, due to the fact, that the content's size is 0 when being initiated. Can I trigger some kind of re-initiate? Thanks in advance!

**Comment by scmaverick** [comment]
I have the same problem even in unhidden environments when the text inserted is too long.

**Comment by mauriciorossetto** [comment]
To solve this issue you need to put a ng-if="showToggle" over a toggle tag,  and in your controller you need to do the magic:

In an activate function put this:
            showToggle = false;

            angular.element(document).ready(function () {
                showToggle = true;
            });

**Comment by bertysentry** [comment]
Fixed in version 0.4.1, thanks!
