### ISSUE TITLE
Inside collapsed elements the toggle will not render to its real size

### ISSUE THREAD

**Issue by JPVenson** [ziscloud/angular-bootstrap-toggle#39]
When using the Toggle directive the control does not expand its height or width to display the text:

```
<div class="form-group">
	<label class="col-md-2 control-label">
		Net/Gross
	</label>

	<div class="col-md-10">
		<toggle ng-model="netGrossToggle"
				ng-change="controller.WorksheetAsserts.NetGrossToggle(netGrossToggle)">
		</toggle>
	</div>
</div>
```

![image](https://user-images.githubusercontent.com/6794763/47791404-ed4d7f00-dd19-11e8-8895-d18b4d4ed785.png)

**Comment by dgsqrs** [comment]
I have the same issue using 0.4.0

**Comment by bertysentry** [comment]
I'm sorry I cannot reproduce.

Here's the Plunkr showing `<toggle>` inside a `form-group`, and working correctly:
[https://plnkr.co/edit/LOp8CX?p=preview](https://plnkr.co/edit/LOp8CX?p=preview)

Did I miss something?

**Comment by dgsqrs** [comment]
Well from my side, I always have the issue, whatever is the parent element.
Do I miss something from 0.1.3 upgrade ? I simply update my bower.json without any other modification.

**Comment by JPVenson** [comment]
I will change the title. It has something todo with a collapsed element!.

as seen here:
https://plnkr.co/edit/YOhriq5ldYvIDIzX8MFC?p=preview

If the toggle button is inside a collapsed element the width and height calculation will not work:

```
  // Calculate the propery width
                        if (!self.width) {
                          var wrapperComputedWidth = Math.max(
                            self.onElement.scrollWidth,
                            self.offElement.scrollWidth
                          ) + Math.max(self.handleElement.scrollWidth, 16) / 2 + 2;
                          self.width = wrapperComputedWidth + 'px';
                        }

                        // Calculate the proper height
                        if (!self.height) {
                            var wrapperComputedHeight = Math.max(
                              self.onElement.scrollHeight,
                              self.offElement.scrollHeight) + 2;
                            self.height = wrapperComputedHeight + 'px';
                        }
```

This should be also true for other elements that are hidden in view and lazy loaded

**Comment by bertysentry** [comment]
I see the same behavior. This is weird: if you replace:
```html
<div class="collapse" ng-class="{'in': collapsed}">
```
with:
```html
<div ng-show="collapsed">
```
it works like a charm!

I don't know how the `collapse` style class works, but there is something weird here...

**Comment by JPVenson** [comment]
`collapse ` changes the display style to `display: non;` and `collapsed in` sets it to `display: block;`

on the other hand ng-show sets it to `display: none !important;`

this is the only difference i see from my side.

**Comment by JPVenson** [comment]
https://plnkr.co/edit/clSwIj9dZ5YdxsVTAuAe?p=preview

**Comment by JPVenson** [comment]
Proposed Change:

Adding the IntersectionObserver as an event to jquery:

```
if (window.IntersectionObserver) {
	$.event.special.visibility = {
		setup: function () {
			function event(visibility) {
				var e = $.Event("visibility");
				e.visible = visibility;
				return e;
			}
			var element = this;
			var $element = $(this);
			var observer = new IntersectionObserver(function (entries) {
				var e = event($element.is(':visible'));
				($.event.dispatch || $.event.handle).call(element, e);
			}, {
				root: document.body
			});
			observer.observe(this);
			$.data(this, 'observer', observer);
		},
		teardown: function () {
			var observer = $.data(this, 'observer');
			if (observer) {
				observer.unobserve(this);
				$.removeData(this, 'observer');
			}
		}
	};
};
```

wrapping the evaluation of size into an function:

```
var evaluateSize = function (reevaluate) {
	// Calculate the propery width
	if (!self.width || reevaluate) {
		var wrapperComputedWidth = Math.max(
				self.onElement.scrollWidth,
				self.offElement.scrollWidth
			) +
			Math.max(self.handleElement.scrollWidth, 16) / 2 +
			2;
		self.width = wrapperComputedWidth + "px";
	}

	// Calculate the proper height
	if (!self.height || reevaluate) {
		var wrapperComputedHeight = Math.max(
				self.onElement.scrollHeight,
				self.offElement.scrollHeight) +
			2;
		self.height = wrapperComputedHeight + "px";
	}
};
```

then instead of calling the evaluateSize function just once when starting, we attach ourself onto the visibility event of query and reevaluating the style:

```
var jElement = $(this.onElement);
if (!jElement.is(":visible")) {
	jElement.on("visibility", () => {
		if (jElement.is(":visible")) {
			evaluateSize(true);
			self.computeStyle();
		}
	});
}
evaluateSize(false);
```

**Comment by JPVenson** [comment]
or with deregistration:

```
if (!jElement.is(":visible")) {
	jElement.on("visibility.toggle", () => {
		if (jElement.is(":visible")) {
			evaluateSize(true);
			self.computeStyle();
			jElement.off("visibility.toggle");
		}
	});
}
```

**Comment by fishan** [comment]
Hi! Any solution to this bug?

**Comment by JPVenson** [comment]
@fishan https://github.com/ziscloud/angular-bootstrap-toggle/pull/40

**Comment by almothafar** [comment]
Any chance to know when this will be pushed? right now revert back to 0.1.3...

**Comment by JPVenson** [comment]
@almothafar thank you for the reminder. I will try to refactor it the way @bertysentry has recommanded today.

**Comment by JPVenson** [comment]
@almothafar @fishan fix has been merged into master

**Comment by almothafar** [comment]
@JPVenson  the latest version seems not working still?

![image](https://user-images.githubusercontent.com/13887564/48983246-07019c80-f0f5-11e8-8148-28bf2e40ab7e.png)

**Comment by JPVenson** [comment]
@almothafar thats sad that your client are pissed of it because you did not test it after upgrade -.-.

Can you create an example how to reproduce it on a fiddle?

**Comment by bertysentry** [comment]
@almothafar Are you sure you're using version 0.4.1 (and not 0.4.0)?

Also please remember that you can always force a fixed size using the `width` and `height` attributes (not ideal, but it's still a workaround)

**Comment by almothafar** [comment]
@JPVenson I tested on stage, but it seems 0.1.3 cached then because he confirmed that everything is fine when I went to prod, seems it got no cached version, the same story from my side, anyway he is not super tech guys, so I can't blame anybody, anyways, not a big deal.

@bertysentry yes I'm totally sure, i'll just for it to stick on 0.1.3 for now.
