### ISSUE TITLE
Why is the height set?

### ISSUE THREAD

**Issue by jonteferm** [ziscloud/angular-bootstrap-toggle#5]
Hey, why is this done? When I add the toggle in my html and sett the size to xs - it will ignore this and set another, calculated, height of the element. If I remove this - it works according to the size I specified.     

 if (wrapperHeight < wrapperComputedHeight && self.size !== 'btn-xs' && self.size !== 'btn-sm') {
              $scope.wrapperStyle.height = wrapperComputedHeight + 'px';
            } else {
              $scope.wrapperStyle.height = wrapperHeight + 'px';
            }

**Comment by AT-Jerome** [comment]
Hello, same for me.
I have to remove the code to calculate the height and width.
regards

**Comment by dumith-eranga** [comment]
same here.

**Comment by hazz1925** [comment]
Same for me too. 
Is there any plan to resolve this?

**Comment by imajedi4ever** [comment]
Same here.

**Comment by jcq** [comment]
For the record, this bug appears in the 0.1.2 version, but not in 0.1.1, and it almost certainly has to do with [this commit](https://github.com/ziscloud/angular-bootstrap-toggle/commit/4c705ceae574e0eb5cfc1b1ddda793fc094a794a#diff-95f767240048e89063f81f65c88b18c2) from Oct 2015. 

The bug doesn't appear on the demo site, but I assume that might not actually be using 0.1.2 version of the minified JS...?

**Comment by nexeh** [comment]
I also have the issue and mention it so late because i have a fresh install and the issue persists.

**Comment by bertysentry** [comment]
Same here. I will have a look at it. Wait for the next PR! ;-)

**Comment by bertysentry** [comment]
Issue is fixed, please close, thanks!
