### ISSUE TITLE
How do i set the width myself ?

### ISSUE THREAD

**Issue by Xsmael** [ziscloud/angular-bootstrap-toggle#6]
How do i set the width myself ?

**Comment by rrowlands** [comment]
Agreed, I'm also having issues with the width not sizing correctly based on the label.

**Comment by gopal-g** [comment]
Yep width is added in-line not able to style it ! :(

**Comment by rrowlands** [comment]
I found a fork which adds this functionality:

https://github.com/aehrc/angular-bootstrap-toggle/commits/master

**Comment by kasikn77** [comment]
I had the same problem. 
If you want to make button wider you can set:
`.toggle.btn{
  min-width: 145px;
}`
:)

**Comment by Xsmael** [comment]
I dont even remember where and why i needed this, anyways thakns for your answers hope it helps others too!
