### ISSUE TITLE
size property is not working

### ISSUE THREAD

**Issue by alminyana** [ziscloud/angular-bootstrap-toggle#9]
I have implemented angular-bootstrap-toggle for show/hide layers of data with OpenStreetMaps and OpenLayers3 and the switch functionality is working fine, but I can't set a lower size for the component.
I'm using the size property as the documentation says.
Many thanks

**Comment by rperetz** [comment]
Got the same issue.

**Comment by UgurAsaner** [comment]
+1

**Comment by bertysentry** [comment]
This is fixed in version 0.4.0. Please close the issue to confirm this is fixed. Thanks!

**Comment by bertysentry** [comment]
This has actually been fixed in version 0.4.1 (for real, now! ;-) ).
